// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Wappirest.Data.Models;

namespace Wappirest.Data.Models
{
    public partial interface IFacturaDbContextProcedures
    {
        Task<int> SP_GUARDAR_PRODUCTOAsync(int? codigo, string nombre, int? stock, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_INSERTAR_DETALLEAsync(int? presupuesto, int? id_detalle, int? producto, int? cantidad, double? precio, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_INSERTAR_MAESTROAsync(string cliente, int? vigencia, OutputParameter<int?> id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_PRODUCTO_POR_CODIGOResult>> SP_RECUPERAR_PRODUCTO_POR_CODIGOAsync(int? codigo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_PRODUCTOSResult>> SP_RECUPERAR_PRODUCTOSAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_REGISTRAR_BAJA_PRODUCTOAsync(int? codigo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
