// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Wappirest.Data.Models
{
    public partial class SP_RECUPERAR_PRODUCTO_POR_CODIGOResult
    {
        public int codigo { get; set; }
        [StringLength(50)]
        public string n_producto { get; set; }
        public int stock { get; set; }
        public bool esta_activo { get; set; }
        public double? precio { get; set; }
    }
}
